### PR TITLE
Fix requestParam and add pathParam

### LINKED ISSUE #39: [🚀] Add request and query parameter
You want to be able to set query and request parameter

### PR DESCRIPTION
**Pull request by finnWellers**
closes #39

### CODE REVIEW

File: src/main/java/de/fearnixx/jeak/service/controller/testImpls/TestController.java [hunk 1]
```diff
@@ -14,7 +14,7 @@ public DummyObject hello() {
         return new DummyObject("Finn", 20);
     }
 
-    @RequestMapping(method =  RequestMethod.GET, endpoint = "/info/:name")
+    @RequestMapping(method =  RequestMethod.GET, endpoint = "/info")
```
Comment (MarkTwoFive) [inline src/main/java/de/fearnixx/jeak/service/controller/testImpls/TestController.java:17]: Wasn't this previously an example of a path parameter instead of a request parameter?

**Review by MarkTwoFive — APPROVED** [review]
